{% set name = "pytest-session2file" %}
{% set version = "0.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b7bdc19c17acaf3991e6592efc570abf5c6d800905f031ce2570b173ec71309a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pytest

test:
  imports:
    - pytest_session2file

about:
  home: https://github.com/BuhtigithuB/pytest_session2file
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE.txt
  summary: pytest plugin to save failure or test session information to a file

extra:
  recipe-maintainers:
    - beckermr
